---
version: "3.9"
services:

  latest:
    image: ghcr.io/valorad/wcnexus.com:latest
    restart: always
    user: "1000"
    volumes:
      - [/path/to/appsettings.Production.yaml]:/workspace/www/wcnexus.com/appsettings.Production.yaml
      - [/path/to/secrets.yaml]:/workspace/www/wcnexus.com/secrets.yaml
    networks:
      - main

# Remember to create this docker network manually!
networks:
  main:
    external:
      name: main
